### ISSUE TITLE
Conflicts with 'rebuild allempty all filtered decks enhanced fork' add on

### ISSUE THREAD

**Issue by jaredagordon** [noobj2/Anki-Advanced-Review-Bottombar#11]
Enabling this add-on removes the 'empty all' and 'rebuild all' buttons from aforementioned add-on .

**Comment by noobj2** [comment]
I'll look into that next time I get some free time -_-

**Comment by noobj2** [comment]
hey, just tried to fix it. installed the rebuild all & empty all add-on.
![image](https://user-images.githubusercontent.com/63994740/102693404-97a4fb00-422f-11eb-9ba8-493bebaeeabf.png)

everything's fine on windows.
please comment if you still have the issue :)
