### ISSUE TITLE
Suspend Button

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [noobj2/Anki-Advanced-Review-Bottombar#13]
Hello! Thanks for the effort developing this addon.  
It's possible to add a "suspend" button on cards?  
At least do you have any idea on how to do that?

**Comment by noobj2** [comment]
I can try to do that.
but I'm a bit busy atm -_-
I'll try to add that as soon as I can

**Comment by noobj2** [comment]
Hi
I'm updating the add-ons
just wanted to ask if you still needed this option

**Comment by noobj2** [comment]
Seems you don't -\_-
So I'm closing this issue
