### ISSUE TITLE
Skip button issue?

### ISSUE THREAD

**Issue by kumamir** [noobj2/Anki-Advanced-Review-Bottombar#15]
I'm not sure if this is an issue or I don't know how to use the skip button, but I thought the skip button takes the current card and places it at the end of the review pile, no?

Whenever I press "skip" the review stack number decreases but the card doesn't go to the back of the review stack at all, it comes back after some cards. And since I'm skipping difficult vocab in my Japanese deck, after some time only the skipped cards are left and they just rotate. Even after I skip all the cards until the review number has decreased to zero (it then goes into negatives) it still just loops the 30-ish difficult cards that I skipped, and I have like 200+ cards in my deck.

So again, I might be wrong on how the skip button should function, but if not, what's going on? :O 

I have Anki version 2.1.35 (84dcaa86)

**Comment by noobj2** [comment]
the skip button just skips a card and puts it randomly in deck.
if you wanna study all the cards that you skip later, you can use built-in "Bury" option
it buries the cards so then you can unbury them and review them
![image](https://user-images.githubusercontent.com/63994740/106754937-cdb50780-6642-11eb-91b0-201ae4cb4b7d.png)

**Comment by kumamir** [comment]
Is there a reason the skip button then removes cards? The more you skip the more cards disappear from the review deck altogether.

**Comment by noobj2** [comment]
it doesn't remove them. it's just the counter. exit the deck and open it again and the counter goes back to normal

**Comment by xnaa** [comment]
For me the skip button doesnt put the card randomly in the deck, all of my skips come back around within less than 30 seconds. Is there any way to set how long from pressing skip until I see the card again?

**Comment by noobj2** [comment]
the skip button does no scheduling. all the scheduling is done by anki so there's currently no way to set the time for them to come back. but you can use the "bury" option instead and then "unbury" buried cards when you want to see them again.
