### ISSUE TITLE
I activated neon colours but they only show up as white in dark mode and grey in light mode I am on version 2.1.35

### ISSUE THREAD

**Issue by ogvie** [noobj2/Anki-Advanced-Review-Bottombar#16]
please help

**Comment by noobj2** [comment]
hey,
you can change colors in "colors tab"
[image: image.png]
one thing to note tho, when you first try to change colors of buttons,
you'll have to check the check box "Custom Review Button Colors" and then
choose the colors you want
[image: image.png]
lemme know if this helped you (or not LOL)

best :D

**Comment by noobj2** [comment]
you can change colors in "colors tab"
one thing to note tho, when you first try to change colors of buttons,
you'll have to check the check box "Custom Review Button Colors" and then
choose the colors you want
![image](https://user-images.githubusercontent.com/63994740/112752482-8dda2300-8fe8-11eb-9e50-178f0244b9db.png)

**Comment by noobj2** [comment]
I assume that fixed your problem. Gonna close the issue.
