### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by sefaangin** [noobj2/Anki-Advanced-Review-Bottombar#17]
Hello, firstly thanks for this perfect addon. I just want to ask you about a new specialty, changing the speed of the sound in flashcards. There are some add-ons but they don't work on Macbooks.  So it will be perfect if you add this specialty to this addon or if you would like of course you can create a new one:) For example it would be perfect if the speed of the sound changes 0.1-+ (from 0.5 to 2.0) It is very useful while language learning. Thanks in advance :)

**Comment by noobj2** [comment]
Hi. Thank you for your kind words :) 
Currently I'm really busy with my university -_- So I kinda can't work on anything new (or work on minor bugs that users have found in other add-ons). 
But I'll add your request to my to-do list and will start working on it as soon as I get free -_- (Summer break most likely)

**Comment by airdroptr1** [comment]
Hi,

Thanks for your reply :) Then i will be waiting for it, enjoy your classes
:)

Best regards

noobj2 ***@***.***>, 21 Nis 2021 Çar, 09:50 tarihinde şunu
yazdı:

**Comment by noobj2** [comment]
hey, I'm working on the add ons and I'm trying to update them. 
wanted to ask if you have found any add-on that does what you need.

**Comment by airdroptr1** [comment]
Hi, actually there are some addons to change the speed, but they work on only windows. I could not find an addon working on macbook. :( The addons i used on windows was 1413404470 or 1067025219. I hope it helps :)

**Comment by noobj2** [comment]
these add-ons are pretty old
I'll try to find a way to make them work on mac too -_- but as I'm not actually a programmer (just a mere student) I make no promises -_-

**Comment by airdroptr1** [comment]
Yes you are right, unfortunately they are very old. You are doing perfect job with addons :) Thank you so much in advance.
