### ISSUE TITLE
Skip just resets the card, doesn't actually skip

### ISSUE THREAD

**Issue by rumDMC** [noobj2/Anki-Advanced-Review-Bottombar#20]
Just updated to 2.1.46 and noticed the skip button isn't working for me. No new addons were downloaded, all that was done was an update from 2.1.35 to 2.1.46. It will reset the card from the answer side back to the question side, but it does not insert it later into the deck. It occurs for all cards (new, learning review) and all templates.

I also can't get the skip shortcut to work (I never have, regardless of anki build) which would be nice but isn't necessary.

**Comment by noobj2** [comment]
https://user-images.githubusercontent.com/63994740/129241326-fe4108f2-ccca-40dc-9e1f-762a06fcc872.mp4

as you see, it works fine
can you disable all other add-ons and see if it works?

**Comment by rumDMC** [comment]
Is this still the correct addon code: https://ankiweb.net/shared/info/1136455830
I've deleted and redownloaded ARBB, disabled all other addons, restarted Anki, and I'm still not able to skip cards

**Comment by noobj2** [comment]
hmmm, that's weird
go to `Tools -> Add-ons` then click on `Advanced Review Bottombar` then click on `View Files` and then open `config.json` and copy its content and send them here so I could use the same add-on settings as your add-on

and what OS are you using? I wonder if that's the problem...

**Comment by rumDMC** [comment]
{
	"  Button Colors": true,
	"  Speed Focus Add-on": false,
	"  More Overview Stats": false,
	"  Settings Menu Place": 0,
	"  Style Main Screen Buttons": true,
    " Review_ Active Button Indicator": 1,
	" Review_ Hover Effect": 1,
    " Review_ Buttons Style": 0,
		" Review_ Bottombar Buttons Style": 0,
    " Review_ Custom Colors": false,
		" Review_ Custom Review Button Text Color": false,
		" Review_ Custom Active Indicator Color": false,
		" Review_ Cursor Style": 0,
		" Review_ Button Transition Time": 500,
		" Review_ Button Border Radius": 5,
		" Review_ Colored Dues": true,
	"Button_   Info Button": true,
  	"Button_   Skip Button": true,
	"Button_   Undo Button": false,
	"Button_   Hide Hard": false,
	"Button_   Hide Good": false,
	"Button_   Hide Easy": false,
	"Button_  Custom Button Sizes": false,
    "Button_ Shortcut_ Skip Button": "c",
    "Button_ Shortcut_ Info Button": "f4",
	"Button_ Shortcut_ Undo Button": "x",
	"Button_ Position_ Info Button": "left",
	"Button_ Position_ Skip Button": "middle left",
	"Button_ Position_ Undo Button": "middle right",
	"Button_ Height_ All Bottombar Buttons": 40,
	"Button_ Width_ Edit Button": 150,
	"Button_ Width_ Show Answer Button": 150,
	"Button_ Width_ Info Button": 150,
	"Button_ Width_ Skip Button": 150,
	"Button_ Width_ More Button": 150,
	"Button_ Width_ Review Buttons": 150,
	"Button_ Width_ Undo Button": 150,
	"Button Label_ Study Now": "Study Now",
	"Button Label_ Edit": "Edit",
	"Button Label_ Show Answer": "Show Answer",
	"Button Label_ More": "More",
	"Button Label_ Info": "Info",
	"Button Label_ Skip": "Skip",
	"Button Label_ Undo": "Undo Review",
	"Button Label_ Again": "Again",
	"Button Label_ Hard": "Hard",
	"Button Label_ Good": "Good",
	"Button Label_ Easy": "Easy",
    "Card Info sidebar_ Number of previous cards to show": 0,
    "Card Info sidebar_ theme": 0,
    "Card Info sidebar_ Created": true,
    "Card Info sidebar_ Edited": true,
    "Card Info sidebar_ First Review": true,
    "Card Info sidebar_ Latest Review": true,
    "Card Info sidebar_ Due": true,
    "Card Info sidebar_ Interval": true,
    "Card Info sidebar_ Ease": true,
    "Card Info sidebar_ Reviews": true,
    "Card Info sidebar_ Lapses": true,
		"Card Info Sidebar_ COrrect Percent": true,
		"Card Info Sidebar_ Fastest Review": true,
		"Card Info Sidebar_ Slowest Review": true,
    "Card Info sidebar_ Average Time": true,
    "Card Info sidebar_ Total Time": true,
    "Card Info sidebar_ Card Type": true,
    "Card Info sidebar_ Note Type": true,
    "Card Info sidebar_ Deck": true,
    "Card Info sidebar_ Tags": true,
		"Card Info Sidebar_ Note ID": false,
		"Card Info Sidebar_ Card ID": false,
    "Card Info sidebar_ Sort Field": true,
    "Card Info sidebar_ Current Review Count": true,
    "Card Info sidebar_ Font": "consolas",
    "Card Info sidebar_ number of reviews to show for a card": 0,
		"Card Info sidebar_ Auto Open": false,
    "Card Info sidebar_ warning note": false,
	"Color_  General Text Color": "#ffffff",
	"Color_ Active Button Indicator": "#ffffff",
	"Color_ Bottombar Button Text Color": "#FF1111",
	"Color_ Bottombar Button Border Color": "#FF1111",
	"Color_ Custom Bottombar Button Text Color": false,
	"Color_ Custom Bottombar Button Border Color": false,
    "Color_ Again": "#BA0C0C",
    "Color_ Again on hover": "#FF1111",
    "Color_ Hard": "#BF720F",
    "Color_ Hard on hover": "#FF9814",
    "Color_ Good": "#20A11C",
    "Color_ Good on hover": "#33FF2D",
    "Color_ Easy": "#188AB8",
    "Color_ Easy on hover": "#21C0FF",
		"Tooltip": true,
		"Tooltip Timer": 500,
		"Tooltip Text Color": "#000",
		"Tooltip Style": 0,
		"Tooltip Position": [100, -100],
		"ShowAnswer_ Border Color Style": 0,
		"ShowAnswer_ Ease1": 200,
		"ShowAnswer_ Ease2": 250,
		"ShowAnswer_ Ease3": 300,
		"ShowAnswer_ Ease4": 350,
		"ShowAnswer_ Ease1 Color": "#FF1111",
		"ShowAnswer_ Ease2 Color": "#FF9814",
		"ShowAnswer_ Ease3 Color": "#33FF2D",
		"ShowAnswer_ Ease4 Color": "#21C0FF"
}

**Comment by rumDMC** [comment]
I'm using Windows 10 if that makes a difference

**Comment by gustavosmendes** [comment]
Hello! I'm having the same problem.

**Comment by gustavosmendes** [comment]
{
	"  Button Colors": true,
	"  Speed Focus Add-on": false,
	"  More Overview Stats": false,
	"  Settings Menu Place": 0,
	"  Style Main Screen Buttons": true,
    " Review_ Active Button Indicator": 1,
	" Review_ Hover Effect": 1,
    " Review_ Buttons Style": 0,
		" Review_ Bottombar Buttons Style": 0,
    " Review_ Custom Colors": false,
		" Review_ Custom Review Button Text Color": false,
		" Review_ Custom Active Indicator Color": false,
		" Review_ Cursor Style": 0,
		" Review_ Button Transition Time": 500,
		" Review_ Button Border Radius": 5,
		" Review_ Colored Dues": true,
	"Button_   Info Button": true,
  	"Button_   Skip Button": true,
	"Button_   Undo Button": false,
	"Button_   Hide Hard": false,
	"Button_   Hide Good": false,
	"Button_   Hide Easy": false,
	"Button_  Custom Button Sizes": false,
    "Button_ Shortcut_ Skip Button": "c",
    "Button_ Shortcut_ Info Button": "f4",
	"Button_ Shortcut_ Undo Button": "x",
	"Button_ Position_ Info Button": "left",
	"Button_ Position_ Skip Button": "middle left",
	"Button_ Position_ Undo Button": "middle right",
	"Button_ Height_ All Bottombar Buttons": 40,
	"Button_ Width_ Edit Button": 150,
	"Button_ Width_ Show Answer Button": 150,
	"Button_ Width_ Info Button": 150,
	"Button_ Width_ Skip Button": 150,
	"Button_ Width_ More Button": 150,
	"Button_ Width_ Review Buttons": 150,
	"Button_ Width_ Undo Button": 150,
	"Button Label_ Study Now": "Study Now",
	"Button Label_ Edit": "Edit",
	"Button Label_ Show Answer": "Show Answer",
	"Button Label_ More": "More",
	"Button Label_ Info": "Info",
	"Button Label_ Skip": "Skip",
	"Button Label_ Undo": "Undo Review",
	"Button Label_ Again": "Again",
	"Button Label_ Hard": "Hard",
	"Button Label_ Good": "Good",
	"Button Label_ Easy": "Easy",
    "Card Info sidebar_ Number of previous cards to show": 0,
    "Card Info sidebar_ theme": 0,
    "Card Info sidebar_ Created": true,
    "Card Info sidebar_ Edited": true,
    "Card Info sidebar_ First Review": true,
    "Card Info sidebar_ Latest Review": true,
    "Card Info sidebar_ Due": true,
    "Card Info sidebar_ Interval": true,
    "Card Info sidebar_ Ease": true,
    "Card Info sidebar_ Reviews": true,
    "Card Info sidebar_ Lapses": true,
		"Card Info Sidebar_ COrrect Percent": true,
		"Card Info Sidebar_ Fastest Review": true,
		"Card Info Sidebar_ Slowest Review": true,
    "Card Info sidebar_ Average Time": true,
    "Card Info sidebar_ Total Time": true,
    "Card Info sidebar_ Card Type": true,
    "Card Info sidebar_ Note Type": true,
    "Card Info sidebar_ Deck": true,
    "Card Info sidebar_ Tags": true,
		"Card Info Sidebar_ Note ID": false,
		"Card Info Sidebar_ Card ID": false,
    "Card Info sidebar_ Sort Field": true,
    "Card Info sidebar_ Current Review Count": true,
    "Card Info sidebar_ Font": "consolas",
    "Card Info sidebar_ number of reviews to show for a card": 0,
		"Card Info sidebar_ Auto Open": false,
    "Card Info sidebar_ warning note": false,
	"Color_  General Text Color": "#ffffff",
	"Color_ Active Button Indicator": "#ffffff",
	"Color_ Bottombar Button Text Color": "#FF1111",
	"Color_ Bottombar Button Border Color": "#FF1111",
	"Color_ Custom Bottombar Button Text Color": false,
	"Color_ Custom Bottombar Button Border Color": false,
    "Color_ Again": "#BA0C0C",
    "Color_ Again on hover": "#FF1111",
    "Color_ Hard": "#BF720F",
    "Color_ Hard on hover": "#FF9814",
    "Color_ Good": "#20A11C",
    "Color_ Good on hover": "#33FF2D",
    "Color_ Easy": "#188AB8",
    "Color_ Easy on hover": "#21C0FF",
		"Tooltip": true,
		"Tooltip Timer": 500,
		"Tooltip Text Color": "#000",
		"Tooltip Style": 0,
		"Tooltip Position": [100, -100],
		"ShowAnswer_ Border Color Style": 0,
		"ShowAnswer_ Ease1": 200,
		"ShowAnswer_ Ease2": 250,
		"ShowAnswer_ Ease3": 300,
		"ShowAnswer_ Ease4": 350,
		"ShowAnswer_ Ease1 Color": "#FF1111",
		"ShowAnswer_ Ease2 Color": "#FF9814",
		"ShowAnswer_ Ease3 Color": "#33FF2D",
		"ShowAnswer_ Ease4 Color": "#21C0FF"
}

Also using Windows 10;

**Comment by noobj2** [comment]
I don't really know why it's not working for you guys -_- my guess is that another add-on is causing skip button not to work
can you two go to `Help -> About` and click on `Copy debug info` and then paste the debug info here

now that two people have issue with skip button there's a better chance I can find out what's causing the problem

**Comment by rumDMC** [comment]
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-08-12 20:34:54
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['Anki-autoLapseNewInterval-latest', 0, 'None', '']
    AMBOSS add-on ['0amboss_addon', 2021-07-13T18:21, 'None', mod]
    Add Table ['1237621971', 2021-07-10T13:37, 'None', mod]
    Advanced Browser ['874215009', 2021-07-22T17:14, 'None', mod]
    Advanced Copy Fields ['1898445115', 2019-05-03T14:46, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2021-08-03T10:27, 'None', mod]
    Anki Persistence ['1051511270', 2020-09-01T15:32, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T15:24, 'None', mod]
    Asset Manager ['656021484', 2021-04-05T16:24, 'None', '']
    Auto Ease Factor ['1672712021', 2021-03-21T14:11, 'None', mod]
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-07-29T08:55, 'None', '']
    Batch Editing ['291119185', 2019-06-02T14:47, 'None', '']
    BetterSearch ['1052724801', 2021-08-04T16:51, 'None', '']
    Card Info During Review ['2179254157', 2021-02-05T05:22, 'None', '']
    Cardistry 2 Dynamically Adjust New Cards ['1535078906', 2020-09-03T16:52, 'None', '']
    Closet For Anki ['272311064', 2021-04-12T10:09, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-13T15:40, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2021-07-07T00:28, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2021-07-31T01:57, '6.7', mod]
    Extended Tag AddEdit Dialog ['1135507717', 2021-05-18T20:29, 'None', mod]
    External Note Editor for the Browser ['browser_external_note_editor', 2020-03-10T13:42, 'None', '']
    Field Modifier Random Item Fork for 21 ['1940275457', 2019-04-11T11:43, 'None', '']
    Five Finger Silver New Answer Button Graph ReLrn Stats ReMemorize Plan9-0 ['2047355215', 2019-06-04T14:27, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T12:06, 'None', '']
    HoochieBaby Queue Controller  Day-Lrn Q ['1847358755', 2020-11-22T21:54, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T22:21, 'None', '']
    Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-14T21:16, 'None', '']
    Leaderboard ['41708974', 2021-06-16T15:40, 'None', mod]
    More Decks Stats and Time Left ['1556734708', 2021-01-27T04:09, 'None', mod]
    Postpone cards review ['1152543397', 2021-01-28T18:20, 'None', mod]
    Pretzel Logic Retention Benchmarking ['1168065472', 2020-04-24T23:13, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T02:26, 'None', '']
    Push Paradox Sibling Cardistry ['1797395052', 2020-04-04T00:40, 'None', '']
    Reset Ease ['947935257', 2020-12-27T09:59, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T02:35, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T09:23, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2021-06-21T12:05, 'None', mod]
    Set Randomizer ['set_randomizer', 0, 'None', mod]
    Show total review count in main screen ['1730200873', 2020-07-25T10:06, 'None', '']
    Show total time spent in main screen ['1238121460', 2020-07-19T04:36, 'None', '']
    Special Fields ['1102281552', 2021-06-20T17:27, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-10-05T19:48, 'None', '']
    Symbols As You Type ['2040501954', 2021-03-21T22:17, 'None', '']
    Symbols ['1461102936', 2019-08-24T20:11, 'None', mod]
    True Retention ['613684242', 2019-10-05T19:50, 'None', '']
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T14:43, 'None', mod]
    load balancer ['1417170896', 2020-08-05T19:58, 'None', '']
    pasteOCR ['1746010116', 2020-12-28T22:27, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1046608507 1051511270 1052724801 1102281552 1103084694 1135507717 1136455830 1143540799 1152543397 1168065472 1237621971 1238121460 1374772155 1417170896 1436550454 1461102936 1535078906 1556734708 1672712021 1730200873 1746010116 1781298089 1797395052 1847358755 1898445115 1940275457 2040501954 2047355215 2179254157 225180905 24411424 266436365 272311064 291119185 385888438 41708974 538351043 613684242 656021484 817108664 874215009 947935257
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Enhance main window ['877182321', 2020-12-22T23:42, 'None', mod]
    Language Tools - Learn Foreign Languages with Anki ['771677663', 2021-07-20T05:27, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T15:13, 'None', '']
    Move Reviews from Weekends and Holidays works with already learnt and mobile ['1222550498', 2020-10-01T07:24, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-09-19T14:52, 'None', mod]
    ReMemorize Rescheduler with sibling and logging v142 ['323586997', 2020-11-20T00:27, 'None', mod]
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T16:13, 'None', '']



Thank you so much for looking into it. It makes a huge difference.

**Comment by rumDMC** [comment]
I just made a test profile and activated all of the same addons that my original has and the skip button is working fine on it. But when I switch back to my original profile, skip still doesn't work. Not sure if that will help you or not, but it doesn't appear to be an addon interfering with it?

**Comment by noobj2** [comment]
it most likely is another add-on interfering with the skip button.
you said that you had disabled all other add-ons previously on your profile but the skip button didn't work, right?
but this time you disabled all the other add-ons on another profile and this time the skip buttons worked.

I think that this is most likely caused by another add-on. I was hoping for @gustavosmendes to send the debug info too, so I could narrow down the list of the add-ons that might cause skip not to word.

anyways, I think I'll have to look into all your active add-ons source codes (the one's that I can access - some of your add-ons are  not public, and some of them are no longer available) hope I can find the add-on causing skip not to work.

meanwhile, can you confirm that skip doesn't work on your main profile even when you disable all the other add-ons? -\_- thanks in advance

**Comment by gustavosmendes** [comment]
Hi,
I Will send later, Sorry!

**Comment by rumDMC** [comment]
I think you misread me, here's what happens (I did these steps again just now to make sure it's still happening):
When I make a new profile and keep all of my addons **active**, I can skip cards fine. 
When I **toggle off** all other addons on my original profile it wont work. 
(I am closing out of anki between toggling the addons off and trying to skip cards)

It's like the profile is what is messing it up and not the addons. Could be completely wrong, just hoping that bit of info helps. Again, thank you so much

**Comment by noobj2** [comment]
> Hi,
> I Will send the debug later, Sorry!!
> But doesnt Work even when disable all the other addons

That'd be really nice 
thank you

**Comment by noobj2** [comment]
> I think you misread me, here's what happens (I did these steps again just now to make sure it's still happening):
> When I make a new profile and keep all of my addons **active**, I can skip cards fine.
> When I **toggle off** all other addons on my original profile it wont work.
> (I am closing out of anki between toggling the addons off and trying to skip cards)
> 
> It's like the profile is what is messing it up and not the addons. Could be completely wrong, just hoping that bit of info helps. Again, thank you so much

hmmm, this is a bit weird -\_-
some add-ons can have different settings for different profiles.
anyways, I'll start looking into the source codes of the add-ons and will try to find out what's wrong.
the bugs that I can't reproduce myself are really a pain to deal with -\_-

thanks for the extra information, that'll help me narrow down the add-on list even more

**Comment by rumDMC** [comment]
If you can think of any other way I can help just let me know

**Comment by noobj2** [comment]
> If you can think of any other way I can help just let me know

Sure :D
thank you ;)

**Comment by gustavosmendes** [comment]
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-08-13 23:46:58
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Review Bottom Bar ['1136455830', 2021-08-03T11:27, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1136455830
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2021-07-26T07:47, 'None', '']
    Advanced Browser ['874215009', 2021-07-22T18:14, 'None', '']
    Always On Top ['1760080335', 2019-06-29T03:45, 'None', '']
    Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T13:57, 'None', '']
    Batch Editing ['291119185', 2019-06-02T15:47, 'None', '']
    BetterSearch ['1052724801', 2021-08-04T17:51, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2021-07-07T01:28, 'None', mod]
    Extended Tag AddEdit Dialog ['1135507717', 2021-05-18T21:29, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T10:23, 'None', '']
    Special Fields ['1102281552', 2021-06-20T18:27, 'None', mod]
    Symbols As You Type ['2040501954', 2021-03-21T23:17, 'None', '']
    remove linebreaks  do word wrap ['2028179508', 2021-04-11T20:36, 'None', '']

**Comment by dae** [comment]
I'm guessing they're using the v3 scheduler, which will return the same results each time getCard() is called.

**Comment by gustavosmendes** [comment]
Indeed, it worked normally when I deactivated the v3 scheduler

**Comment by noobj2** [comment]
> I'm guessing they're using the v3 scheduler, which will return the same results each time getCard() is called.

thank you. I didn't even know that there was a new scheduler -\_-  now I can try and find a new way to make it work -\_-

**Comment by noobj2** [comment]
Added new method for skipping cards. It'll be enabled by default if you use V3 scheduler.
I suggest you read the changelog in "About" tab in Settings Menu to understand the difference between the two methods

**Comment by rumDMC** [comment]
Thank you so much.
