### ISSUE TITLE
Height of the settings window is a little to big

### ISSUE THREAD

**Issue by keikiki** [noobj2/Anki-Advanced-Review-Bottombar#21]
Hi,
first of all I thank you very much for your all efforts programming an add-on for Anki!
And now for something completely different... My screen resolution is 1366x768 and I cannot see the buttons on the bottom of the default settings window. It is also not possible to reduce the window size.
Could you reduce the default height of the settings window, please?
Many greetings,
Keikiki

**Comment by noobj2** [comment]
Hey
I had that in mind when I was coding the settings menu, so it should be working fine.
![image](https://user-images.githubusercontent.com/63994740/130224367-6a389e7d-4a29-4d1b-818d-add8812bbe27.png)
and for some tabs that are too many options, the tabs are scrollable.

buy anyways, can you send a screenshot of your settings menu so I'd know approximately how much I should decrease the height?

Thanks :D

**Comment by keikiki** [comment]
No problem. Here you are:

![Screenshot 2021-08-20 14-56-14](https://user-images.githubusercontent.com/43296087/130237341-7e9be989-8cfd-4225-993c-c436834ad73d.jpg)

**Comment by noobj2** [comment]
Fixed.
