### ISSUE TITLE
Under Misc setting "More overview stats" to "detailed" seems to cause problems on 2.1.46 

### ISSUE THREAD

**Issue by hemanggs** [noobj2/Anki-Advanced-Review-Bottombar#22]
This ,on opening any deck.
![image](https://user-images.githubusercontent.com/89329624/130342085-a4abdab5-02e4-4508-9bfd-e31e61e806ea.png)

Really helpful plugin though ty.

**Comment by noobj2** [comment]
It should be fixed now
