### ISSUE TITLE
Skip button brokes style of the card

### ISSUE THREAD

**Issue by rah-90** [noobj2/Anki-Advanced-Review-Bottombar#24]
https://user-images.githubusercontent.com/89321123/130866377-1cfc6ff5-d2ef-47db-b7ed-f5f31799b5b1.mp4

My debug info:
    
    Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-08-25 23:22:14
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    ARLPCG ['1642554134', 2021-08-09T18:02, 'None', '']
    Add Hyperlink ['318752047', 2021-07-10T20:40, 'None', '']
    Add Parent Tag To Every Tag In A Deck ['543106186', 2019-11-21T04:30, 'None', '']
    Add Table ['1237621971', 2021-07-10T19:37, 'None', mod]
    Add Tag and Move 21 ['1923996023', 2020-02-24T00:25, 'None', '']
    Add a tag to notes with missing media ['2027876532', 2019-08-25T00:23, 'None', '']
    Add card default copies current cards tag and deck in ['676957592', 2021-07-18T16:21, 'None', '']
    Add note id ['1672832404', 2020-12-06T12:44, 'None', '']
    Adjust Sound Volume ['2123044452', 2021-05-05T13:24, 'None', '']
    Advanced Browser ['874215009', 2021-07-22T23:14, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-12-24T14:47, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2021-08-22T10:09, 'None', mod]
    Always On Top ['1760080335', 2019-12-24T15:37, 'None', '']
    Anki Persistence ['1051511270', 2020-09-01T21:32, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T21:24, 'None', '']
    Anki Time anti-distraction helper ['998250600', 2020-09-12T23:27, '20.9.12i228', '']
    Anki-Translator Forked and updated to Anki 21 ['702944768', 2020-02-13T15:45, 'None', '']
    AnkiConnect ['2055492159', 2021-07-14T02:59, 'None', '']
    AnkiFlash Importer Vietnamese English Japanese Chinese French flashcards ['1129289384', 2021-02-21T17:11, 'None', '']
    Asset Manager ['656021484', 2021-04-05T22:24, 'None', '']
    Auto Ease Factor ['1672712021', 2021-03-21T20:11, 'None', '']
    AutoDefine - Automatically define vocabulary words with pronunciations and image ['2136497008', 2020-11-16T01:16, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-07-29T14:55, 'None', '']
    Basic Printing Support ['1025789669', 2020-02-24T08:12, 'None', '']
    Batch Editing ['291119185', 2019-08-24T21:29, 'None', '']
    Batch Remove Formatting eg bold italics etc ['1734822644', 2019-12-24T13:49, 'None', '']
    BetterSearch ['1052724801', 2021-08-04T22:51, 'None', '']
    Bold the cloze v218 ['213022609', 2019-10-10T04:39, 'None', '']
    Browser Card Info Bar ['2140680811', 2020-11-03T13:27, 'None', '']
    Browser MaximizeHide TableEditor ['1819291495', 2021-05-27T18:47, 'None', '']
    Browser Resizer ['1435775540', 2021-08-01T23:11, 'None', '']
    Bury Cousins related cards that arent siblings ['1072815885', 2021-07-20T03:23, 'None', '']
    CTRLF5 to Refresh the Browser ['1347728560', 2019-08-24T23:00, 'None', '']
    Change Card Creation Times ['217650262', 2019-08-24T23:49, 'None', '']
    Change Order of Review Cards in Regular Decks ['3731265543', 2019-12-24T14:52, 'None', '']
    Clickable Tags v11 ['380714095', 2020-03-22T15:56, 'None', '']
    Closet For Anki ['272311064', 2021-04-12T16:09, 'None', '']
    Cloze Anything ['330680661', 2019-12-30T00:17, 'None', '']
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T05:12, 'None', '']
    Collapsible Fields ['1896168623', 2021-03-07T17:08, 'None', '']
    Colours of Marked Suspended and Flagged Cards ['1590588489', 2019-12-17T02:41, 'None', '']
    Control Audio ['1591259314', 2020-08-25T09:17, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-24T00:03, 'None', '']
    Copy notes ['1566928056', 2021-07-31T15:42, 'None', '']
    Correct Answers Graph ['993120073', 2020-03-24T14:57, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-13T22:40, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-12-24T14:45, 'None', '']
    Custom Styles font color background colour classes ['1899278645', 2021-03-03T02:41, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T23:01, 'None', '']
    Deadline2 ['723639202', 2021-05-02T06:45, 'None', mod]
    Deck Counts NowLater ['1836212767', 2020-09-09T17:33, 'None', '']
    Duplicate Selected Notes ['2126361512', 2019-12-24T14:44, 'None', '']
    Duplicate and Reorder ['1114271285', 2020-11-14T01:01, 'None', '']
    Dynamic Fields ['1747470707', 2021-08-02T14:28, 'None', '']
    Edit Field During Review Cloze ['385888438', 2021-07-31T07:57, '6.7', mod]
    Editor Autocomplete for Anki 21 ['925419294', 2020-10-06T23:51, 'None', '']
    Enhanced Cloze for Anki 21 ['1990296174', 2021-08-19T15:17, 'None', '']
    Export Cards As Text ['1112021968', 2021-07-08T09:57, 'None', '']
    Export Single Tag For Sharing ['960563361', 2021-08-21T03:57, 'None', '']
    Export in CSV format ['1478130872', 2019-12-24T15:48, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2021-05-19T02:29, 'None', '']
    External Note Editor for the Browser ['1996266159', 2020-03-31T22:59, 'None', '']
    Fastbar- with nightmode support ['46611790', 2021-08-22T22:33, 'None', '']
    Field History ['1247884413', 2019-12-24T14:00, 'None', '']
    Field Modifier Random Item Fork for 21 ['1940275457', 2019-04-11T17:43, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-08-05T21:38, 'None', '']
    Find Missing Words ['754868802', 2019-12-26T21:38, 'None', '']
    ForgotToStudy ['1074757548', 2020-01-18T01:16, 'None', '']
    Free Anki Enumeration Tool ['268751365', 2021-01-28T04:54, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T06:12, 'None', '']
    High Yield Tags ['1918380616', 2021-08-07T02:48, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T19:06, 'None', '']
    Hint Hotkeys ['1844908621', 2019-09-15T01:35, 'None', '']
    Hyphenate Words ['1140138750', 2021-01-16T11:02, 'None', '']
    Image Editor ['307397307', 2021-06-21T01:24, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    Image Style Editor ['1593969147', 2020-12-17T15:06, 'None', mod]
    Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-15T04:16, 'None', '']
    Insert Randomized Lists multiple choice ['1280092568', 2019-08-24T23:25, 'None', '']
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2021-07-25T00:17, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2020-12-29T00:40, 'None', '']
    Life Drain ['715575551', 2021-04-03T08:26, 'None', '']
    Links between notes cards to open browser and previewer ['1126950429', 2020-12-23T06:51, 'None', '']
    Lists to Anki Convert bulletpoint lists or Org files to Anki Cards ['1029306148', 2020-04-08T05:44, 'None', '']
    Long term backups ['529955533', 2019-08-24T23:05, 'None', '']
    Media Import ['1531997860', 2019-12-24T15:05, 'None', '']
    Mindmap from tag hierarchy ['965278890', 2021-05-20T14:49, 'None', '']
    Mini Format Pack ['295889520', 2019-08-24T21:55, 'None', '']
    Modified reviewer context menu search with browser search ['930944997', 2019-10-17T03:58, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T11:09, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T21:13, 'None', '']
    More Overview Stats ['2116130837', 2021-05-29T13:24, 'None', '']
    Multiple Choice for Anki ['1566095810', 2021-03-18T19:50, 'None', '']
    New Format Pack ['1187194862', 2021-08-10T02:41, 'None', '']
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-08-14T00:59, 'v4.1.8', mod]
    Number of Decks ['1358364553', 2019-12-11T21:01, 'None', '']
    Open Added Today from Reviewer ['861864770', 2019-02-22T21:19, 'None', '']
    Papercards - export  print flashcards to paper ['2042118948', 2021-05-14T03:58, 'None', '']
    Pass Rate Bar ['1371632081', 2020-10-16T20:48, 'None', '']
    Persistent Editor ['1686259334', 2021-02-12T02:05, 'None', '']
    Picmonic Anki Add-On ['40737180', 2021-07-28T00:27, 'None', mod]
    Pop-up Dictionary beta ['153625306', 2019-03-23T19:32, 'None', '']
    Postpone cards review ['1152543397', 2021-01-29T01:20, 'None', '']
    Preview any cloze number ['915063177', 2020-02-28T15:01, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T08:26, 'None', '']
    Quick Colour Changing ['2491935955', 2017-08-28T14:48, 'None', '']
    Quick Field Navigation ['734297936', 2019-12-30T04:24, 'None', '']
    Quick note and deck buttons Fork for 21 ['1331140127', 2021-03-03T01:48, 'None', '']
    Quick tagging 21 ['304770511', 2020-02-12T02:12, 'None', '']
    Quizlet to Anki 21 Importer with audio support ['1362209126', 2020-09-10T19:28, 'None', '']
    Rebuild All  Empty All for Anki 21 ['1810938259', 2019-08-24T23:41, 'None', '']
    Regex Search  Wildcard Matching on Field Names ['2044559350', 2020-02-09T19:49, 'None', '']
    Reloadbackup menu option ['883617253', 2020-01-04T21:47, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T16:14, '20.12.13i151', '']
    Remote Decks Anki collaboration using Google Docs ['911568091', 2021-03-08T20:57, 'None', '']
    Remove card history ['2089200096', 2018-04-23T08:50, 'None', '']
    Removes Empty Note Types for 21 ['530953383', 2019-08-24T23:58, 'None', '']
    Reset Card Scheduling ['300884351', 2019-08-20T07:47, 'None', '']
    Reset Ease ['947935257', 2020-12-27T16:59, 'None', '']
    Reset Profile ['1976367957', 2020-12-28T14:53, 'None', '']
    Reset Review Stats ['742319784', 2020-01-06T22:10, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Scale Images ['1312865748', 2021-06-05T11:53, 'None', '']
    Schedule Priority customize intervals ['580930132', 2021-07-26T22:56, 'None', '']
    Search Bar ['1251668918', 2020-09-09T23:55, 'None', '']
    Search and Replace Tags ['138501288', 2019-08-03T14:25, 'None', '']
    Search in formatted text in any fields ['1126516755', 2020-06-01T22:03, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2021-06-21T18:05, 'None', mod]
    Session Timer ['1287298831', 2020-06-30T18:35, 'None', '']
    Show total review count in main screen ['1730200873', 2020-07-25T16:06, 'None', '']
    Show total time spent in main screen ['1238121460', 2020-07-19T10:36, 'None', '']
    Showing time in browser ['1243668133', 2020-03-11T00:13, 'None', '']
    Simple Timer and Stopwatch for Anki 21 ['1423272642', 2018-01-25T01:03, 'None', '']
    Smart Copy ['2026164196', 2020-09-12T20:23, 'None', '']
    Sort by Card Type Note Type or Deck Name ['1872117511', 2019-12-02T09:44, 'None', '']
    Special Fields ['1102281552', 2021-06-20T23:27, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-08-24T22:55, 'None', '']
    Spelling Police ['1410276506', 2020-03-03T04:13, 'None', '']
    Statistics for Note Types Card Types and Tags ['16703369', 2020-07-20T04:11, 'None', '']
    Straight Reward ['957961234', 2021-01-11T14:37, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-25T19:29, 'None', '']
    Symbols As You Type ['2040501954', 2021-03-22T04:17, 'None', '']
    Symbols ['1461102936', 2019-04-18T22:21, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-07T03:31, 'None', '']
    Tag Entry Enhancements v2 ['536796161', 2020-11-10T13:28, 'None', '']
    TagSelectorV2 ['1022577188', 2021-08-07T13:28, 'None', '']
    Textograph Tree Structured flashcards ['1073960055', 2020-09-07T16:41, 'None', '']
    Throughput Historical ['485345973', 2019-08-24T21:26, 'None', '']
    Time Spent Creating Cards ['1178407876', 2020-07-01T22:08, 'None', '']
    Time per revised card graph ['1703703955', 2021-01-27T02:12, 'None', '']
    Toggle Tags via ReviewerEditorBrowser Context Menu ['2088508994', 2019-01-01T01:50, 'None', '']
    Transfer scheduling data from one card to another ['94685914', 2020-09-18T11:23, 'None', '']
    True Retention ['613684242', 2019-07-24T09:49, 'None', '']
    True Retention by Card Maturity ['923360400', 2019-08-03T14:33, 'None', '']
    Word autocomplete for Anki 21 ['131336778', 2020-12-06T16:52, '20.12.6i158', '']
    Wrapper meta-addon ['396502676', 2021-05-19T03:10, 'None', '']
    Ze Frozen Fields ['94610912', 2021-02-12T02:06, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2020-05-08T15:16, 'None', '']
    confirm deletion ['263363568', 2019-08-24T23:40, 'None', '']
    copy note contents to new Add window from Browser Reviewer Add EditCurrent ['759018284', 2019-10-13T15:19, 'None', '']
    export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2020-09-20T13:50, 'None', '']
    extended editor for field for tables searchreplace  ['805891399', 2020-11-24T02:08, 'None', '']
    paste plainunformatted text ['107041104', 2020-11-08T15:24, 'None', '']
    pasteOCR ['1746010116', 2020-12-29T05:27, 'None', '']
    postponedelay addon update for selected addons ['1655214124', 2021-07-10T19:34, 'None', '']
    put ALL due learning cards first modified v2 support ['1807121582', 2019-12-24T14:08, 'None', '']
    remove linebreaks  do word wrap ['2028179508', 2021-04-12T01:36, 'None', '']
    when is next learning card due today due ['563204849', 2020-09-13T15:51, 'None', '']
    zzz Force Choose On Add Card ['789889430', 2020-02-13T23:53, 'None', '']
    zzz Switch Note Type Hotkey ['565948788', 2020-02-14T09:34, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1022577188 1025789669 1029306148 1046608507 1049863218 1051511270 1052724801 107041104 1072815885 1073960055 1074757548 109531687 1102281552 1112021968 1114271285 1126516755 1126950429 1129289384 1135507717 1136455830 1140138750 1143540799 1152543397 1172858842 1178407876 1187194862 1237621971 1238121460 1243668133 1247884413 1251668918 1280092568 1287298831 1312865748 131336778 1331140127 1347728560 1358364553 1362209126 1371632081 1374772155 138501288 1410276506 1423272642 1435775540 1436550454 1461102936 1463041493 1478130872 1508357010 1531997860 153625306 1556734708 1566095810 1566928056 1590588489 1591259314 1593969147 1642554134 1655214124 16703369 1672712021 1672832404 1686259334 1703703955 1730200873 1734822644 1746010116 1747470707 1760080335 1781298089 1807121582 1810938259 1819291495 1836212767 1844908621 1872117511 1896168623 1898445115 1899278645 1918380616 1923996023 1933645497 1940275457 1949865265 1967530655 1976367957 1988760596 1990296174 1996266159 2026164196 2027876532 2028179508 2040501954 2042118948 2044559350 2055492159 2084557901 2088508994 2089200096 2116130837 2123044452 2126361512 213022609 2136497008 2140680811 217650262 225180905 2491935955 263363568 266436365 268751365 272311064 291119185 295889520 300884351 304770511 307397307 318752047 330680661 3731265543 380714095 385888438 396502676 40737180 46611790 485345973 516643804 529955533 530953383 536796161 538351043 543106186 561945101 563204849 565948788 580930132 613684242 656021484 668156440 676957592 702944768 715575551 723639202 734297936 738807903 742319784 754868802 759018284 789889430 805891399 817108664 861263371 861864770 874215009 883617253 911568091 915063177 923360400 925419294 930944997 94610912 94685914 947935257 957961234 960563361 965278890 993120073 998250600
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['Beautify Anki', 0, 'None', mod]
    AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2021-07-26T12:47, 'None', '']

**Comment by noobj2** [comment]
> I will re-enable my add-ons one by one and will let you know if I found the suspected add-on.

This is really nice. Thank you in advance :D

**Comment by rah-90** [comment]
Finally found it.

It's caused by **Persistent Editor**: https://ankiweb.net/shared/info/1686259334

**Comment by noobj2** [comment]
Thank you again for finding the add on :) this means a lot

I'll read the source code for that add-on as soon as I get some free time and will let you know if I can do anything about the conflict by changing certain parts of ARBb code

**Comment by noobj2** [comment]
Hi again.
Finally read the source and did some testing.

this issue isn't because of a conflict, it's just an issue that Persistent Editor causes.
You can disable all other add-ons and just enable Persistent Editor then try burying a card (which is anki's built-in feature). When you do that, you can see that this add-on resets all card styling.

so unfortunately there's nothing I can change in ARBb code to fix this.
I read the code, and this line is causing the issue `reviewer_did_show_question.append(stop_fading_on_question)` in `src -> reviewer.py` file.

**Comment by rah-90** [comment]
Thank you Mr. noobj2.
Really appreciate your time & replying.

I think Persistent Editor is not critical add-on for me. I well just disable it.

**Comment by noobj2** [comment]
No problem :)
