### ISSUE TITLE
Feature Request: Make grading hotkeys work even without revealing reverse of card.

### ISSUE THREAD

**Issue by davidskau** [noobj2/Anki-Advanced-Review-Bottombar#28]
This isn't a huge deal, and might have some risks of users thinking they know all of what's on the back of a card when they actually don't, but I could sometimes see a benefit to being able to grade myself on a card without flipping it first - mostly for the "easy" option, to use with basic card types when I have the concept down so solidly I already know what's on the back of the card.

**Comment by noobj2** [comment]
Since nobody seems to be interested in this feature, I'll close the issue -\_- sorry
