### ISSUE TITLE
sidebar default position

### ISSUE THREAD

**Issue by Nevieltez** [noobj2/Anki-Advanced-Review-Bottombar#33]
I would like it if there could be some way I could configure the sidebar (info) to always show up on the left side of the screen instead of the right. Currently I manually have to move it to the left

**Comment by noobj2** [comment]
I'll add that in a future update. Meanwhile you can make it show up in the left side by doing these steps:
1. Go to "Tools -> Add-ons"
2. Click on ARBb add-on and then press "View Files" Button
3. Open "Card_info.py" and go to line 47 (you can open it in windows notepad or download notepad++)
4. Replace the line with this `mw.addDockWidget(Qt.LeftDockWidgetArea, dock)`

here's a picture
![image](https://user-images.githubusercontent.com/63994740/152695199-c423dff7-f010-407b-860d-2d570eded994.png)

**Comment by Nevieltez** [comment]
Thanks a lot dude, sorry for the late reply

**Comment by noobj2** [comment]
it's alright
Added the option in the settings (Sidebar tab)
