### ISSUE TITLE
Description's deck

### ISSUE THREAD

**Issue by thiagornela** [noobj2/Anki-Advanced-Review-Bottombar#35]
Hi, everyone.

How could I access the descriptions of deck with this extension?

**Comment by noobj2** [comment]
Hi 
I never have seen that button -\_- 
I don't know if it was added in an update or it has always been there. But it's my mistake -\_- and I'll fix it in the next update
and thank you for reporting the issue ;)

**Comment by thiagornela** [comment]
Thank you so much!

**Comment by noobj2** [comment]
thank YOU for reporting the issue.
Please don't close the issue until I fix it (so I won't forget to fix it)

**Comment by noobj2** [comment]
fixed

**Comment by thiagornela** [comment]
Hi.
After update, It is not showing the descriptions of deck. Would it be possible to add it again, please?
