### ISSUE TITLE
Better code for the new skip engine

### ISSUE THREAD

**Issue by ROOMBON** [noobj2/Anki-Advanced-Review-Bottombar#41]
(Solves the problem that if anki closes in the middle of the review the card does not come out of the bury)
#fixme - different config for each profile

`
        
    from aqt import mw
    from aqt import gui_hooks
    from aqt.utils import showInfo
    from aqt.reviewer import Reviewer
    
    #// getting config information
    config = mw.addonManager.getConfig(__name__)
    skipped_cards = []
    #// Bury and mark for unburying
    def burySkipped():
        skipped_cards.append(mw.reviewer.card.id)
        mw.checkpoint(_("Bury"))
        mw.col.sched.buryCards([mw.reviewer.card.id])
        config['skipped_cards'] = skipped_cards
        mw.addonManager.writeConfig(__name__, config)
        mw.reset()
    
    def try_unburySkipped():
        global skipped_cards
        mw.col.sched.unbury_cards(skipped_cards)
        skipped_cards=[]
        mw.reset()
    
    #// Unbury skipped cards upon exiting review screeen
    gui_hooks.reviewer_will_end.append(try_unburySkipped)
    
    #// Unbury skipped cards when exiting anki
    def try_unbury_Skipped_on_restart(state, _oldstate):
        if state == "deckBrowser":
            mw.col.sched.unbury_cards(config['skipped_cards'])
            config['skipped_cards'] = []
            mw.addonManager.writeConfig(__name__, config)
            mw.reset()
    
    gui_hooks.state_will_change.append(try_unbury_Skipped_on_restart)
    def test():
        showInfo("{}".format(mw.col.sched.version))

`

**Comment by noobj2** [comment]
hey
thanks, I'll check it out when I update the add-on

**Comment by noobj2** [comment]
Closing Anki mid-review was something that I hadn't thought about. Thank you for the fix.
I changed the code a bit, now skipped cards will be unburied upon closing Anki.
