### ISSUE TITLE
button border radius

### ISSUE THREAD

**Issue by aboali1hassona** [noobj2/Anki-Advanced-Review-Bottombar#42]
Why the _button border radius_ set as maximum at **50** px

- i hope if we can increase this limit.
- [windous 10 - anki 2.1.54]

![image](https://user-images.githubusercontent.com/91283119/178559860-9ff86359-dd5f-45b8-93e9-b688a5a09caa.png)

**Comment by noobj2** [comment]
hey
It was just my personal preference -\_-
I'll remove it or increase the limit in the next update

**Comment by noobj2** [comment]
changed the limit to 100px (100px is basically a circle, anything more than that doesn't make sense)
