### ISSUE TITLE
small request

### ISSUE THREAD

**Issue by sepehr72** [noobj2/Anki-Advanced-Review-Bottombar#43]
Hey. Awesome add-on and thank you for your work.

Is it possible to add more buttons such that all my learning steps are visible? So if my learning steps are 2m 10m 20m 1d, can the bottom bar show all of these steps instead of just 2m for again, 5m for hard, 10m for good, and 4d for easy?

**Comment by noobj2** [comment]
Hey. 
there's already an add-on for that. It's called [More answer buttons for new cards](https://ankiweb.net/shared/info/2089145805)
