### ISSUE TITLE
[Compatibility] Bottombar shows the intervals given by Anki's built-in scheduling, not the custom scheduling.

### ISSUE THREAD

**Issue by L-M-Sherlock** [noobj2/Anki-Advanced-Review-Bottombar#44]
I implement a custom scheduling to modify the interval of Anki. But `Advanced Review Bottom Bar` doesn't shows the intervals given by my scheduling.

For more details, please see: https://github.com/open-spaced-repetition/fsrs4anki/issues/23

**Comment by noobj2** [comment]
Hey
I'll check out your add on when i have some free time and see if I can make custom intervals show instead of the default intervals.

You can also try to modify ARBb and make it work with your add-on, I'll gladly accept the pull request and update ARBb on ankiweb.

**Comment by L-M-Sherlock** [comment]
> Hey I'll check out your add on when i have some free time and see if I can make custom intervals show instead of the default intervals.
> 
> You can also try to modify ARBb and make it work with your add-on, I'll gladly accept the pull request and update ARBb on ankiweb.

I propose this PR to solve this problem, looking forward to your review: #45

**Comment by noobj2** [comment]
tested it, caused the error"V3CardInfo has no attribute called states"
tried to fix it by directly importing "SchedulingStates" couldn't get it to work.
checked anki source code more to try and find a way to access states or be able to import "SchedulingStates" couldn't find a way.
can't really put more time in fixing it rn. so I reverted the changes until I can find a way to fix it.

I would gladly accept prs fixing this if you found a way to get it to work. but for now, the conflict stays I guess -_-

**Comment by L-M-Sherlock** [comment]
Which version does this error happen? It’s OK in Anki 2.1.55. Maybe it should to check the version of Anki?

**Comment by noobj2** [comment]
latest stable version (2.1.54 Qt6).
I'll download the beta and test it, if it works I'll update the add-on on the website just for the anki > 2.1.55

**Comment by noobj2** [comment]
It works on Anki 2.1.55
I updated the add-on on ankiweb
it should be fixed now
