### ISSUE TITLE
Custom size button falling of the screen

### ISSUE THREAD

**Issue by panuwat54** [noobj2/Anki-Advanced-Review-Bottombar#46]
I want a change bottom button height but when I use custom size and put number larger than 25 px
All of them will start falling of the screen

I use windows 10 and my anki version is 2.1.49

here is the picture 
https://ibb.co/pKLknwx (anki in fullscreen)

https://ibb.co/LST9zVD (anki in minimize window)

and here is others addon I use
https://ibb.co/NYZ8Z2w

**Comment by Nayelianne** [comment]
Also experiencing this problem. I'm used to having my anki window much narrower for comfort, but if I don't stretch it a lot even the non-oversized buttons end up broken due to apparently being in fixed positions instead of adapting to the size of the window.

**Comment by noobj2** [comment]
hey
thanks for the report.
I've been super busy with my exams lately and I couldn't work on the add-on
I'll fix this issue as soon as I can -_-

**Comment by noobj2** [comment]
Fixed
