### ISSUE TITLE
Bottom bar getting cut off

### ISSUE THREAD

**Issue by Hithereui** [noobj2/Anki-Advanced-Review-Bottombar#47]
Hi, I am unsure as to whether this is an issue with this addon specifically, but I thought you might be able to help anyway. My bottom bar is cut off and looks like this: 
![image](https://user-images.githubusercontent.com/94995029/199844022-e31c9f01-9694-4f71-b69b-dd7541ba64d8.png)
![image](https://user-images.githubusercontent.com/94995029/199844215-b5753e22-2b1a-42a5-bef3-33437b628301.png)
It appears like this for all decks.
Please help (if you can)!

**Comment by noobj2** [comment]
hey
I've been pretty busy with my college lately -\_- I'll check it out and try to fix the issue if it's caused by ARBb
can you give me your debug info (go to help -> about and then click on "Copy debug info" button) to see your add-ons and anki version?

**Comment by shoudeyunkaijianyueming** [comment]
Anki 2.1.55 (e3c3405f) Python 3.9.7 Qt 6.4.0 PyQt 6.4.0
    Platform: macOS-12.5-x86_64-i386-64bit
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2022-11-18 09:31:07
    
 
    ===Add-ons (active)===
    Advanced Review Bottom Bar ['1136455830', 2022-09-29T21:32, 'None', mod]
    


# I have the same problem as him, here is my message

**Comment by gustavosmendes** [comment]
> hey I've been pretty busy with my college lately -_- I'll check it out and try to fix the issue if it's caused by ARBb can you give me your debug info (go to help -> about and then click on "Copy debug info" button) to see your add-ons and anki version?

The problem it seems to be caused by css class=stattxt

**Comment by noobj2** [comment]
Fixed
