### ISSUE TITLE
Button Intervals Cut off unless Button Interval Style is Inside the Buttons

### ISSUE THREAD

**Issue by daddydave** [noobj2/Anki-Advanced-Review-Bottombar#48]
Amazing addon! I have been messing with the betas lately, currently at 2.1.55 beta 6.
I see Button Intervals cut off unless the Button Interval Style is Inside the Buttons (in that case, it is not inside the buttons, but at least it is not cut off)

Stock:
![Stock](https://user-images.githubusercontent.com/9300442/204432518-ffd48974-f528-431b-90a0-c19bf8fad2aa.png)

Colored Stock:
![Colored_Stock](https://user-images.githubusercontent.com/9300442/204432555-ac0b990d-083e-44a1-8efa-6b236a64fdc8.png)

Inside the Buttons:
![Inside_the_Buttons](https://user-images.githubusercontent.com/9300442/204432557-99ce5af8-7086-4d19-9e29-b202908b8fc5.png)

This looks similar to the already reported [Due Counts (12 + 34 + 56) being cut off](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/issues/47)

Version ⁨2.1.55 (ca116699)⁩
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Windows 11

**Comment by Nayelianne** [comment]
Really appreciate this tip, the buttons were not adjusting properly to the window size (2.1.49 here) and I had to have the window quite large so buttons wouldn't get weirdly cut off. But changing the Button Interval Style to "Inside the Buttons" seems to have fixed it!

**Comment by cafelinked** [comment]
This issue as well as Due Counts being cut off are replicated in 2.1.55. Qt6. 

I understand with 2.1.55+, Time is now nested inside the buttons, hence when Button Interval Style is switched to Inside the Buttons, the issue is partially fixed.

**Comment by daddydave** [comment]
Relevant post on the Anki forums, it looks like a change will be reverted in 2.1.56, hopefully fixing this. 
https://forums.ankiweb.net/t/bottom-bar-review-and-card-count-cropped-after-update/25471/2
