### ISSUE TITLE
Backup Settings

### ISSUE THREAD

**Issue by kurkasr** [noobj2/Anki-Advanced-Review-Bottombar#49]
Hi. When I try to back up my setting, there is an error. I'm on Mac. 
Error ⁩Caught exception:
Traceback (most recent call last):
  File "/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 2440, in onSaveSettings
    subprocess.Popen(f'explorer /select, "{path_to_file}"')
  File "subprocess", line 951, in __init__
  File "subprocess", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'explorer /select, "Library/Application Support/Anki2/addons21/1136455830\\user_files\\ARBb 24-Dec-2022.json"'

Can you also hide 'easy' button if it's not in a learning phase and show if it's in a learning phase?

**Comment by noobj2** [comment]
Hey,
I've been extremely busy with my exams lately and haven't been able to do much work on the add-on (barely could get some free time to fix a minor issue).
I'll check what's wrong and try to fix it and also add the option to hide easy if the card is in learning phase.
hope you understand -_-

**Comment by noobj2** [comment]
hey, I'm working on the add-on.
do you still have the backup issue?

**Comment by noobj2** [comment]
I don't have a mac to test the add-on on -_-
can you go to "Tools -> Add-ons -> select Advanced Review Bottombar -> click on Open files" then open "user_files" folder and see if the backup file has been created there?

**Comment by noobj2** [comment]
Alright, I changed some stuff that'll hopefully fix the backup issue (not sure if it will tho, couldn't test it)
I've also added the "hide easy button if card is not in learning phase" too
I'll release the new version in a couple of days

**Comment by noobj2** [comment]
fixed and added
