### ISSUE TITLE
Issue with showing the buried count in a deck with Anki 2.1.55

### ISSUE THREAD

**Issue by talkael** [noobj2/Anki-Advanced-Review-Bottombar#50]
in 2.1.5 anki allows seeing how many cards were buried in new learning and review before clicking "study now" this add on removes this feature. Would be great if it was fixed!

**Comment by noobj2** [comment]
thanks for the report.
I'll fix that as soon as possible

**Comment by noobj2** [comment]
hey
I'm working on the add-on bugs.
I don't see anki showing the buried count before clicking on study now.
can you send me a screenshot so I could understand what you mean?

**Comment by talkael** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/109875058/215293866-a3ce4af4-5d1b-4b4e-8664-af6c86d1d31d.png">

I attached the image if you can see the greyish numbers are the ones for buried. This is with disabling the add on

**Comment by noobj2** [comment]
I'm on anki 2.1.56 and I don't have that gray number.
![image](https://user-images.githubusercontent.com/63994740/215294354-5377ca0c-1b35-44aa-a421-69b6fd36455a.png)

maybe that's added by another add-on?
can you open anki while holding down shift (to temporarily disable all the add-ons) and see if you still have that gray number?

**Comment by talkael** [comment]
I did that and it still exists you might not have any cards that need to be buried thats why. You need to have siblings in your news for it to show

**Comment by noobj2** [comment]
fixed

**Comment by talkael** [comment]
Thank you legend
