### ISSUE TITLE
Pointer cursor not working

### ISSUE THREAD

**Issue by TheChilliPL** [noobj2/Anki-Advanced-Review-Bottombar#53]
![image](https://user-images.githubusercontent.com/18823939/211170497-57bc9efe-cc9d-4254-ab67-4b26d934b8a6.png)
![image](https://user-images.githubusercontent.com/18823939/211170504-02051391-0f38-4c69-bb7e-188de358e79c.png)

Anki 2.1.55 (01caec2a)
Python 3.9.15 Qt 6.4.0 PyQt 6.4.0

**Comment by noobj2** [comment]
hey
thanks for the report
I did a quick check and I couldn't figure out what caused the pointer styling not to work (the cursor style in the webview is pointer and it should be working)
I currently don't have much free time to find out what's wrong
I'll put more time into it when I the exams are over and try and fix it -_-

**Comment by noobj2** [comment]
hey
I was working on the add-on.
there's nothing wrong with ARBb, with all add-ons disabled, the pointer style cursor sometimes doesn't work (on the deck names for example)
if you like the cursor style, you can simply install the Qt5 version.
the Qt5 doesn't have this issue.
