### ISSUE TITLE
Button Intervals Off

### ISSUE THREAD

**Issue by Andysk13** [noobj2/Anki-Advanced-Review-Bottombar#55]
The intervals seem a little too far off from the buttons in the image below, so the bottom drawer kinda takes up more screen real estate
![image](https://user-images.githubusercontent.com/104822046/212465535-af9bef2a-6909-420d-90c4-8fce5936f481.png)
Tried setting stock inside buttons to mitigate this, but instead I got a scrollbar that still doesn't show the numbers, top image is how it appears initially and bottom image how it appears upon scrolling down
![image](https://user-images.githubusercontent.com/104822046/212465592-2e9530d9-4636-4fab-a66f-efc79c739dd3.png)
![image](https://user-images.githubusercontent.com/104822046/212465599-3311dbb8-4b69-4f3c-a0de-21ada15c02c4.png)

Fantastic add-on! Had zero gripes with it until now, I assume it's because of all the updates and stuff. Thanks for all your hard work!

**Comment by noobj2** [comment]
fixed
