### ISSUE TITLE
Error after clicking Show Answer

### ISSUE THREAD

**Issue by Yerrun** [noobj2/Anki-Advanced-Review-Bottombar#56]
Error

Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-31 16:49:16

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.reviewer", line 655, in _onTypedAnswer
  File "aqt.reviewer", line 414, in _showAnswer
  File "aqt.reviewer", line 710, in _showEaseButtons
  File "C:\Users\me\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 226, in _answerButtons
    buf += but(ease, label)
TypeError: can only concatenate str (not "NoneType") to str

Even after disabling all other add-ons, the error is still there.

**Comment by noobj2** [comment]
can you update to anki 2.1.57 and see if you still have this issue?
I've tested the add-on on anki 2.1.57 both Qt5 and Qt6 and I don't get any error.
if you still get the error can you backup your ARBb settings and send me the backup file and also explain the steps to replicate this issue?

**Comment by Yerrun** [comment]
Yes, it's still there.

Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-02-01 17:35:34

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.reviewer", line 644, in _onTypedAnswer
  File "aqt.reviewer", line 413, in _showAnswer
  File "aqt.reviewer", line 698, in _showEaseButtons
  File "C:\Users\Jeroen\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 226, in _answerButtons
    buf += but(ease, label)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by noobj2** [comment]
do you get this error on a specific card or on all cards?
can you backup your settings and send the backup file here so I could use your exact settings to replicate the bug?

**Comment by Yerrun** [comment]
Yes it's with all cards.

[https://shorturl.at/IJVY7](url)

**Comment by noobj2** [comment]
hmmm
you sure that's the right link?

**Comment by Yerrun** [comment]
It was, but the url shortener provider is crappy.

[https://zxcion.com/file/file.zip](url)

**Comment by noobj2** [comment]
> It was, but the url shortener provider is crappy.
> 
> [https://zxcion.com/file/file.zip](url)
> 
> copy/paste it in a browser coz clicking doesn't work at github.

you don't need to shorten the link
just send the original link, it's fine

**Comment by Yerrun** [comment]
I exported a deck and installed it under a different profile and then the error was gone. Also on a mobile phone it was working. So it looks like it is related to that profile...

**Comment by Yerrun** [comment]
[https://zxcion.com/file/file.zip](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/issues/url)

**Comment by noobj2** [comment]
> I exported a deck and installed it under a different profile and then the error was gone. Also on a mobile phone it was working. So it looks like it is related to that profile...

alright then
if the issue is gone for you, I'll keep the issue open and see if anybody else reports this.
then I'll start working on the issue to see what's wrong -_-

**Comment by Yerrun** [comment]
okay. As soon as I know more I'll let you know.

Also, should you add-on sync with a mobile phone, because it hasn't yet. Or maybe it's because I still have Anki 2.1.56 installed on my phone?

**Comment by noobj2** [comment]
thank you :D
I really appreciate the report

**Comment by DerevenetsArtyom** [comment]
@noobj2, Hi there!
I've got the same error today, when I've installed the plugin:

Error
...
Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-21 16:11:17
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.reviewer", line 644, in _onTypedAnswer
  File "aqt.reviewer", line 413, in _showAnswer
  File "aqt.reviewer", line 698, in _showEaseButtons
  File "/home/derevenets/.local/share/Anki2/addons21/1136455830/Button_Colors.py", line 226, in _answerButtons
    buf += but(ease, label)
TypeError: can only concatenate str (not "NoneType") to str


Unfortunately, I can't send the backup of my settings, since the feature doesn't work on Linux :sweat_smile: 
I've seen this issue: https://github.com/noobj2/Anki-Advanced-Review-Bottombar/issues/49, but for Linux it is not `isMac`, so non-existing `explorer` gets called and it's crashing.

**Comment by Mutticiu** [comment]
I have the same issue on Mac.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-02-22 11:21:08
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 562, in handler
  File "aqt.reviewer", line 655, in _onTypedAnswer
  File "aqt.reviewer", line 414, in _showAnswer
  File "aqt.reviewer", line 710, in _showEaseButtons
  File "/Users/justus/Library/Application Support/Anki2/addons21/1136455830/Button_Colors.py", line 226, in _answerButtons
    buf += but(ease, label)
TypeError: can only concatenate str (not "NoneType") to str

Same error on 2.1.60: 

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-02-22 11:30:34
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 604, in handler
  File "aqt.reviewer", line 641, in _onTypedAnswer
  File "aqt.reviewer", line 414, in _showAnswer
  File "aqt.reviewer", line 695, in _showEaseButtons
  File "/Users/justus/Library/Application Support/Anki2/addons21/1136455830/Button_Colors.py", line 226, in _answerButtons
    buf += but(ease, label)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by noobj2** [comment]
hey
I'm a bit busy now, I'll check this again (last time I tried I couldn't reproduce the issue and I couldn't find out what was wrong -\_-)

I would appreciate it if you guys could tell me how exactly I can reproduce the issue, questions that might help in finding what's causing the issue would be:
1. does it happen on certain decks? filtered decks? imported decks?
2. does it happen when you do something particular before pressing the button? like suspending a card, burying a card, skipping a card, opening card browser, etc.
3. does it happen on certain card types? cloze, type in the answer, etc.
4. does it happen on a particular profile? or does it still happen if you change the profile?
every single detail that might seem unimportant might help in finding the cause of the issue and helping me reproduce the issue on my device consistently.

as far as I know it's not happening to all the users, there must be something particular causing the add-on to crash; and without knowing what exactly it is, I can't do anything about it.

@DerevenetsArtyom about #49 I didn't know the backup function doesn't work on linux too -\_-
it seems that you're also a python developer and you are running linux, I'd really appreciate if you could fix the backup issue and create a pr.

**Comment by noobj2** [comment]
I was finally able to reproduce this issue and find out what is causing it. #60 

for a quick fix, you can go to `ARBb settings -> styles` and set the `Button Interval Style` to `Colored Stock`

I'll fix the issue in the next update

**Comment by noobj2** [comment]
Fixed
