### ISSUE TITLE
Answer Tooltip - Review Confirmation Tooltip

### ISSUE THREAD

**Issue by phamousq** [noobj2/Anki-Advanced-Review-Bottombar#57]
"Tooltip Position: Fixed Position" seems to scale based on the absolute position of the monitor screen, not the Anki App. "Tooltip Position: On Buttons" allows the positioning of the tooltip to be reactive to the screen size of the Anki app itself. 

I would like to have the tooltip appear close to the top of the Anki window after rating a flashcard in a window that has been resized (not fullscreen). 

Currently, moving the Y-axis slider of "On Buttons" option only moves the tooltip to about the middle of the screen instead of the top of the screen. 

Using "Fixed Position" moves the tool tip unpredictably when using a resized window.

Ani Version info:
Version ⁨2.1.57 (6b7d372c)⁩
Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
on Apple Silicon Macbook

**Comment by noobj2** [comment]
https://user-images.githubusercontent.com/63994740/218251124-65e40fe4-ee5f-4de2-9a7a-24200218665a.mp4

I tested it on windows and it works fine. As I don't have a macbook, I can't test it on them. So until someone that can test the add-on on mac tries to fix this issue, unfortunately I can't do anything about it.
