### ISSUE TITLE
Could you tell me how to export ease, rating of the cards and time on CSV file ?

### ISSUE THREAD

**Issue by Semayuki** [noobj2/Anki-Advanced-Review-Bottombar#59]
The add-on you created is very easy to use.
Thank you very much.
By the way, I edited the add-on you created to change the
1. ease value before learning the card
2. date and time when learning
3. the evaluation of the card when it is learned

I would like to output a csv file with all of them.

Which file of your add-on should I edit and how?
If possible, I would appreciate it if you could attach the Python code. Thank you in advance.

**Comment by noobj2** [comment]
hey
I don't understand what exactly you want to do.
1. card in learning phase don't have an ease factor.
2. learning is a phase and it doesn't have a particular date and time for a card. I'm not sure if you mean date and time of the review in which the card exited the learning phase.
3. I'm not sure if you mean the button that was pressed and caused the card to exit the learning phase and enter review phase.

are these what you want to export?
2. date and time of the last review in learning phase
3. button pressed in the last review in learning phase

**Comment by Semayuki** [comment]
Thank you for your reply.
I apologize for my lack of words.
I think you are right, but I will add something.

In the add-on you created, you can see the value of the ease just before the card was evaluated.
I want to export that value and the time of the moment when the card was evaluated together in a csv file.

If you have any ideas, please let me know.

**Comment by noobj2** [comment]
I did a search if anybody's created an add-on for exporting revlog to a csv file.
this is what I found:
https://www.reddit.com/r/Anki/comments/ecg0lg/export_personal_ankiing_data/

I think it might help you
