### ISSUE TITLE
A mistake (Anki 2.1.60)

### ISSUE THREAD

**Issue by kurkasr** [noobj2/Anki-Advanced-Review-Bottombar#60]
When I uncheck "Show next review time above answer buttons" in Review preferences, there is a mistake. Could you fix that, please?

**Comment by noobj2** [comment]
can you explain a bit more? also a screenshot of the issue would help a lot

**Comment by noobj2** [comment]
Yessss, finally

for a quick fix, you can go to `ARBb settings -> styles` and set the `Button Interval Style` to `Colored Stock`

**Comment by noobj2** [comment]
Fixed
