### ISSUE TITLE
I still have no idea what this does

### ISSUE THREAD

**Issue by dharrison27** [noobj2/Anki-Advanced-Review-Bottombar#61]
There's an awful lot of text to explain what you can do with this add-on. 

Some sample screenshots of the things that can be done, would go a long way.

**Comment by noobj2** [comment]
Hey
Each part of the settings does something and changes some part of anki that I thought adding all the screenshots in the readme would clutter it unnecessarily; and it would be better to let the users experiment with different settings and get the hang of things. I also have included description of what each part of the settings does with screenshots when necessary in the add-on itself (hover your pointer over each item in the settings for a few second and it'll appear).

But I'll try to add more screenshots to the readme file in the future updates, and also create a video of me explaining different settings when I have time.

**Comment by dharrison27** [comment]
Hi!

Thank you for the tweaks! I think the screenshots that you've added are enough. Thank you!
