### ISSUE TITLE
Skip button: New cards are skipped once only

### ISSUE THREAD

**Issue by schrmh** [noobj2/Anki-Advanced-Review-Bottombar#62]
It looks like that the Skip button won't cycle trough all cards that are either new or in learning status.
![image](https://user-images.githubusercontent.com/32062480/229831579-51ad806d-cefd-4315-9423-d32f9b860cd9.png)
Consider this deck. It first skips trough the nine new cards but then cycles between the two cards in learning status instead of cycling trough all eleven cards.

Software:
Anki 2.1.61
Arch Linux

**Comment by noobj2** [comment]
there are two skipping methods which you can choose from in the misc tab in ARBb settings.

- first method is "Next card": it just skips the card without doing doing anything to the card, skipping the card and deciding when to show the card again is completely done by anki and isn't controlled by ARBb.

- the second method it "Bury": as the name suggests, when you skip a card, it buries the card and you have to manually unbury them or when you finish reviewing the cards, it's automatically unbury the skipped cards.
