### ISSUE TITLE
Feature request: wide button style for general buttons

### ISSUE THREAD

**Issue by sudomain** [noobj2/Anki-Advanced-Review-Bottombar#65]
Hello,

First, thank you for the add-on. I'm reviewing cards on my phone via Termux and VNC and having large buttons was a piece of AnkiDroid which I had missed. Your add-on makes Anki way more touch friendly.

I just finished a session of:
1. Guess a button width and height for edit, review and more buttons (I removed info because I hardly use it and it's under the more menu)
2. Put those numbers in the add-on
3. Restart Anki
4. Repeat 1-3 until there are good button sizes

My system is set up now, but it would be great if we could specify percentages of the screen instead of pixels. That or not have to restart Anki for button size changes.

For reference, my X display is running at a 1080x1920 resolution and these are the button widths and heights that I think make it look nice:
![Screenshot_20230430-125802](https://user-images.githubusercontent.com/30786326/235366313-5c2d34a0-0117-440f-a599-6e9f0c27a77c.png)

**Comment by noobj2** [comment]
There's already a button style that adjusts the size of the buttons based on the width of the screen. If you choose the wide button style in the button `Styles -> Button Styles`, the width of the buttons will be adjusted based on the size of your screen. Here's how it looks.


https://user-images.githubusercontent.com/63994740/235388005-861b9c0d-f0a7-4fe0-b113-0f78d0ba83d6.mp4

**Comment by sudomain** [comment]
Sorry, I had missed that. i'm nit-picking here but is there a way to reduce the unused spaced between the review buttons and the general buttons ("info" and "more")? Possibly a wide button style for the general buttons?

**Comment by noobj2** [comment]
I'll add that as a feature when I get some free time

**Comment by sudomain** [comment]
Thank you. I'll change the issue title to reflect that

**Comment by noobj2** [comment]
Added the ability to choose how much of the empty space should be occupied by the review buttons in v3.3.0
You can change it in the Styles tab
