### ISSUE TITLE
Add-on incompatibility (rebuild/empty some or all filtered decks)

### ISSUE THREAD

**Issue by jcznk** [noobj2/Anki-Advanced-Review-Bottombar#66]
Hi, first thank you for the nifty add-on! 

I noticed your add-on interferes with https://ankiweb.net/shared/info/104518886 (rebuild/empty some or all filtered decks)
The add-on normally adds two buttons to deck browser/main window's bottom bar (Rebuild All and Empty All). After installing Advanced Reviewer Bottom Bar, the buttons disappeared (and they reapper if I disable the add-on). I also tried toggling-off Style Main Screen Buttons, but it did not solve the problem.

**Comment by noobj2** [comment]
hey 
Thank you for the report :D
I'll look into it when I get some free time.

**Comment by noobj2** [comment]
Fixed.
You should enable the rebuild/empty all in the add-ons section in Misc tab. this will change the style of the buttons added by this add-on too for a uniform look.
![image](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/63994740/99dcbb74-6484-4ccd-9f39-3ab18cf1729c)

also, disabling the "Style Main Screen Buttons" should now remove conflict with any add-on trying to modify the main screen buttons or deck overview buttons.
