### ISSUE TITLE
Feature request: Ability to replace buttons with custom icons

### ISSUE THREAD

**Issue by blushell99** [noobj2/Anki-Advanced-Review-Bottombar#67]
Would love to be able to customize my own icons to replace buttons, especially the review buttons, but I'm not sure how to do that myself. Ideally there would just be an option for us to add our own images and select which button we want to replace.

**Comment by noobj2** [comment]
That's a very good idea. I was thinking of something like that myself a while ago.
I'll start working on it as soon as the summer break begins.

**Comment by noobj2** [comment]
Hey,
I've been thinking about a way to implement this feature for too long.
but I've decided that implementing this in ARBb would complicate things too much.
maybe I or someone else will create a separate add-on for this.
