### ISSUE TITLE
Part of the Review Buttons texture staying after clicking

### ISSUE THREAD

**Issue by Quarlie** [noobj2/Anki-Advanced-Review-Bottombar#71]
version: 2.1.65

When pressing on review buttons (Again, Hard, Good, Easy), a rectangle with the respective color and its text stay a bit on screen (even when buttons are formatted completly different)

before click:
![Screenshot (982)](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/80974176/6aa82605-0b88-45b8-a35a-067dd407a47f)

after clicking on good:
![Bild_2023-06-21_000157034](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/80974176/cb7348c8-5fcf-43f9-b9a2-b550209cbd8e)

**Comment by noobj2** [comment]
This is the expected behavior. 
To disable this, you can go to settings and disable review confirmation tooltip in answer tooltip tab.
