### ISSUE TITLE
[feature request] respect anki Hide bottom bar during review

### ISSUE THREAD

**Issue by omega3** [noobj2/Anki-Advanced-Review-Bottombar#72]
In new Anki version preferences there is an option "Hide bottom bar during review → Full screen only" feature. Please make this add-on respect this feature. 

While your add-on is great and very useful, when I want to focus fully on review content I use only keyboard to answer. Having larger area when bottom bar is hidden allow more content of a card to appear in review so that I don't need to scroll that frequently.

**Comment by noobj2** [comment]
Hey,
Thanks for the report.
I'll start working on it in a few days.

**Comment by noobj2** [comment]
Fixed in the new release.
You can update the add-on now.
