### ISSUE TITLE
Option to disable Current Card

### ISSUE THREAD

**Issue by omega3** [noobj2/Anki-Advanced-Review-Bottombar#73]
Is it possible to disable Current Card statistics? I usually analyze what happens when I rate card in order to adjust deck settings. As there is no much vertical space I need to scroll down.
Or alternatively disable these again, hard, good, easy statistics.
https://i.imgur.com/ibbhMLI.png

**Comment by noobj2** [comment]
Added a new feature in the Sidebar tab for that.
you can update the add on and check it out.
