### ISSUE TITLE
Make the font size of intervals above buttons adjustable

### ISSUE THREAD

**Issue by Expertium** [noobj2/Anki-Advanced-Review-Bottombar#74]
Currently, there is no way to adjust the font size of intervals displayed above the buttons.
![image](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/83031600/ae805f87-72c7-43ec-b16c-698271206358)

**Comment by noobj2** [comment]
Hey,
I'll add that as an option in the next update.

**Comment by Expertium** [comment]
So, has it been implemented? I can't find it

**Comment by noobj2** [comment]
I'd been busy I just did a quick fix for sidebar in the last update.
But I've already implemented the adjustable intervals. I'll publish an update soon.

**Comment by noobj2** [comment]
Done in v3.5.0
