### ISSUE TITLE
[Anki 23.10 beta 3] Qt.Category.Thing

### ISSUE THREAD

**Issue by khonkhortisan** [noobj2/Anki-Advanced-Review-Bottombar#75]
Q[t|Frame|Palette].[Shape|WindowType|ColorRole].[Panel|Tooltip|Window[Text]]
```py
addons21\1136455830\Tooltip.py:587:'QFrame.Panel' will stop working. Please use 'QFrame.Shape.Panel' instead.
addons21\1136455830\Tooltip.py:591:'Qt.ToolTip' will stop working. Please use 'Qt.WindowType.ToolTip' instead.
addons21\1136455830\Tooltip.py:593:'QPalette.Window' will stop working. Please use 'QPalette.ColorRole.Window' instead.
addons21\1136455830\Tooltip.py:594:'QPalette.WindowText' will stop working. Please use 'QPalette.ColorRole.WindowText' instead.
addons21\1136455830\Tooltip.py:606:to avoid memory leaks, pass an appropriate parent to progress.timer() or use progress.single_shot()
```

**Comment by noobj2** [comment]
Hey, 
Thanks for the report. I'll change them in the next update.

**Comment by khonkhortisan** [comment]
[Anki 23.10 beta 6] this gets upgraded to an error, happens when rating the first card, prevents going to the next card by throwing the error each time I try to rate it
> The Qt5 compatibility code is now off by default, which may break some add-ons that haven't been updated to support Qt6 in the last 2 years. If you find any have broken, please report the issues to the add-on author, and start Anki after setting the env var ENABLE_QT5_COMPAT to 1 to temporarily restore the compatibility code.
```py
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
Información de depuración:
Anki 23.10 (72e57456) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-14 10:11:10
Complementos posiblemente implicados: ⁨Advanced Review Bottom Bar, right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable⁩

Caught exception:
Traceback (most recent call last):
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\850294128\__init__.py", line 137, in newAnswerCard
    _old(self, min(self.mw.col.sched.answerButtons(self.card), ease))
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1136455830\Tooltip.py", line 559, in myTooltip
    showTooltip(text, background_color, tooltip_textColor, button_width, button_height, x_offset, y_offset, period=tooltip_timer)
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1136455830\Tooltip.py", line 587, in showTooltip
    lab.setFrameStyle(QFrame.Panel)
AttributeError: type object 'QFrame' has no attribute 'Panel'
```
workaround:
```py
    #lab.setFrameStyle(QFrame.Panel)
    lab.setFrameStyle(QFrame.Shape.Panel)
    lab.setLineWidth(2)
    lab.setFixedWidth(button_width)
    lab.setFixedHeight(button_height)
    #lab.setWindowFlags(Qt.ToolTip)
    lab.setWindowFlags(Qt.WindowType.ToolTip)
    p = QPalette()
    #p.setColor(QPalette.Window, QColor(background_color))
    p.setColor(QPalette.ColorRole.Window, QColor(background_color))
    #p.setColor(QPalette.WindowText, QColor("transparent"))
    p.setColor(QPalette.ColorRole.WindowText, QColor("transparent"))
```

**Comment by Kikkwa** [comment]
> [Anki 23.10 beta 6] 这会升级为错误，在对第一张卡进行评级时发生，每次我尝试对其进行评级时都会抛出错误，从而阻止转到下一张卡
> 
> > Qt5 兼容性代码现在默认处于关闭状态，这可能会破坏一些过去 2 年来尚未更新以支持 Qt6 的附加组件。  如果您发现任何问题，请向插件作者报告问题，并在将环境变量 ENABLE_QT5_COMPAT 设置为 1 后启动 Anki 以暂时恢复兼容性代码。
> 
> ```python
> Error 
> Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
> Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
> Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
> Información de depuración:
> Anki 23.10 (72e57456) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
> Platform: Windows-10-10.0.19045
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-10-14 10:11:10
> Complementos posiblemente implicados: ⁨Advanced Review Bottom Bar, right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 86, in repl
>   File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\850294128\__init__.py", line 137, in newAnswerCard
>     _old(self, min(self.mw.col.sched.answerButtons(self.card), ease))
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 83, in repl
>   File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1136455830\Tooltip.py", line 559, in myTooltip
>     showTooltip(text, background_color, tooltip_textColor, button_width, button_height, x_offset, y_offset, period=tooltip_timer)
>   File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1136455830\Tooltip.py", line 587, in showTooltip
>     lab.setFrameStyle(QFrame.Panel)
> AttributeError: type object 'QFrame' has no attribute 'Panel'
> ```
> 
> workaround:
> 
> ```python
>     #lab.setFrameStyle(QFrame.Panel)
>     lab.setFrameStyle(QFrame.Shape.Panel)
>     lab.setLineWidth(2)
>     lab.setFixedWidth(button_width)
>     lab.setFixedHeight(button_height)
>     #lab.setWindowFlags(Qt.ToolTip)
>     lab.setWindowFlags(Qt.WindowType.ToolTip)
>     p = QPalette()
>     #p.setColor(QPalette.Window, QColor(background_color))
>     p.setColor(QPalette.ColorRole.Window, QColor(background_color))
>     #p.setColor(QPalette.WindowText, QColor("transparent"))
>     p.setColor(QPalette.ColorRole.WindowText, QColor("transparent"))
> ```

I've encountered the same issue as well. This plugin is essential for my needs, and I hope the author can release an update soon.

**Comment by noobj2** [comment]
I've implemented your suggestions @khonkhortisan and published a new release.
sorry it took me so long, my life's been really busy and kind of chaotic lately.
