### ISSUE TITLE
Blocked From Confirming Answer On Anki 23.10.1

### ISSUE THREAD

**Issue by cdrch** [noobj2/Anki-Advanced-Review-Bottombar#77]
On pressing an answer key, an error pops up instead of allowing me to continue. It worked perfectly fine the day before yesterday. I've tested with a variety of other addons enabled and disabled, as I had added some today, but the problem occurred in all configurations, including one test with Advanced Review Bottombar being the only enabled addon.

I also seem to recall updating at least one addon today...guessing I've been reminded which one that was, though I don't see a recent update here?

Full error log below. It was reproduced several times successfully with varying combinations of addons enabled. Note my added comment - all runs after the first produced line 541 instead of 539 (including in cases with the same addons enabled as the first run), but otherwise all error output was identical.
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-12 19:29:21
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 628, in handler
  File "aqt.reviewer", line 539, in _onAnswerButton           // line 541, in the same function, in some runs
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Carter David\AppData\Roaming\Anki2\addons21\1136455830\Tooltip.py", line 559, in myTooltip
    showTooltip(text, background_color, tooltip_textColor, button_width, button_height, x_offset, y_offset, period=tooltip_timer)
  File "C:\Users\Carter David\AppData\Roaming\Anki2\addons21\1136455830\Tooltip.py", line 587, in showTooltip
    lab.setFrameStyle(QFrame.Panel)
AttributeError: type object 'QFrame' has no attribute 'Panel'
```

**Comment by cdrch** [comment]
Update: I thought that perhaps I *wasn't* on the latest version from GitHub, and installed v3.4.1. This appears to have totally fixed the problem. Feel free to close, though I won't immediately do so as I didn't see this exact problem in the other recent issues so it might be worth glancing at regardless.

**Comment by noobj2** [comment]
The issue has been fixed in newer versions.
