### ISSUE TITLE
"Skip" button inconsistent

### ISSUE THREAD

**Issue by andresduran98** [noobj2/Anki-Advanced-Review-Bottombar#79]
When using the "Skip" button, sometimes it will skip as it is intended to (and keep the card for later), but sometimes pressing the button causes it be buried (to-do card count/queue decreases by 1, and pressing CTRL+Z or "Undo" in the "More" dropdown menu shows a notification that the card was unburied).

**Comment by noobj2** [comment]
Hey
There are two skip methods.
One of them buries the cards, but as soon as you're done reviewing they'll get unburied.

have you chosen the "Next Card" method for skipping cards (in misc tab of the settings) yet the add-on still buries the cards?
If yes, does this happen randomly? Happens on specific decks, cards, card types? 
is there anything I can do to replicate this issue? any info would be much appreciated.
