### ISSUE TITLE
Speed-Focus Add-ons

### ISSUE THREAD

**Issue by havewisdom** [noobj2/Anki-Advanced-Review-Bottombar#8]
https://ankiweb.net/shared/info/1046608507

with speed-focus add-ons,
"answer "again" after" function doesn’t work.
"alert after, show answer after" function still work though.

thank you

**Comment by noobj2** [comment]
hey
sorry took so long to respond
currently I'm busy (life's happened) but I'll work on the issue as soon as possible.
meanwhile you can use the modified version of speed focus (#5 ). I'll let you know when the issue is fixed

**Comment by noobj2** [comment]
took forever -_- but finally an update

if you want to use speed focus, you need to enable the option that's in ARBb settings -> Misc
