### ISSUE TITLE
Button shortcuts reset after restarting Anki

### ISSUE THREAD

**Issue by beejumm** [noobj2/Anki-Advanced-Review-Bottombar#80]
Hey, thanks for this add-on, love it.

One issue I have faced is changing the custom shortcuts, it says to apply the shortcut, to restart Anki.
When I do, the shortcuts default to the original ones, and my edits have been erased.

![image](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/146592804/b44041aa-392b-44df-9267-daa2ec6cf09a)

**Comment by noobj2** [comment]
Hey
Thanks for the report.
I was busy with exams, I'll try to fix it in a few days.

**Comment by noobj2** [comment]
It should be fixed now. Can you confirm?

**Comment by beejumm** [comment]
It's fixed, thanks so much
Sorry for the late reply
