### ISSUE TITLE
Change spaces between buttons.

### ISSUE THREAD

**Issue by XeromX** [noobj2/Anki-Advanced-Review-Bottombar#81]
Newer anki versions require anki window to be quite wide to show edit buttons and for me it's incontinent because I always use many apps at the same time so I like to keep anki window quite narrow. I changed buttons sizes using your extension but it doesn't have any impact .

**Comment by noobj2** [comment]
Hey.
Have you tried setting the position of the skip button to the middle right or middle left?
![image](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/63994740/e1aa9e88-172a-46f7-851d-31f8a4a814da)

**Comment by fabHAgithub** [comment]
Sadly not working with this tip. Still showing "SHOW ANSWER" like before :(
Thanks!
I don't use Linux, it's android app. In my PC, the button it's working!

**Comment by noobj2** [comment]
But anki add-ons aren't supported on android app. you can't install them. I really don't know how you have installed the add-on on the android version of anki let alone why it's not working.
