### ISSUE TITLE
SKIP BUTTON NOT SHOW IN ANDROID APP, ONLY "SHOW ANSWER". PLEASE.

### ISSUE THREAD

**Issue by fabHAgithub** [noobj2/Anki-Advanced-Review-Bottombar#82]
![photo_1_2024-03-19_00-21-58](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/85220859/d4091274-4696-4011-bd27-b6f4b0e7b42b)

As screenshot shows, I can't skip the card anyway. It's normal? I'm using last android version.

**Comment by noobj2** [comment]
Hey, the add-on is not developed for android app. I believe you have installed a linux distro on your android device (?).

fixing the add-on for an unsupported platform isn't my highest priority. But send some more info, I'll try to fix it in the next update (if possible).

**Comment by noobj2** [comment]
but apparently it's because of the new version of anki hiding the buttons when the window is too narrow.
maybe try this fix:
[#81 ](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/issues/81#issuecomment-2093986387)
