### ISSUE TITLE
Answer tooltips not properly aligned on buttons when the sidebar is open

### ISSUE THREAD

**Issue by qappell** [noobj2/Anki-Advanced-Review-Bottombar#83]
After clicking an answer button when the card info sidebar is open and answer tooltips is set to "On Buttons", the tooltip shows up where the answer button would be if the sidebar wasn't open. Please view this [screen recording](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/164906821/289d061d-7cbd-4529-8dba-813bd1503c05) that demonstrates this. I repeated this test afterward with the sidebar closed, and the tooltip functioned properly, appearing centered on the answer button.
(Windows 11, Anki 24.04.1 Qt6, latest add-on as of 5/23/2024)

**Comment by noobj2** [comment]
the position of the button confirmation is all calculated approximately. since the width of the sidebar isn't fixed, I can' do anything about the position of the answer tooltips.
