### ISSUE TITLE
A question about skip button

### ISSUE THREAD

**Issue by frameshift-mutation** [noobj2/Anki-Advanced-Review-Bottombar#84]
What happens exactly when I click on skip (Next card mode)?
Does the interval/ease change in any way?
When do I see the card again? Is it consistent? and based on what?
Thanks for the cool add-on btw

**Comment by noobj2** [comment]
1. Short answer: it just goes to the next card without doing anything to the card you skip.
1. Long answer: Whenever you answer a card, Anki uses a function to fetch the next card. The next card method bypasses the need to answer the current card to show the next card. it basically just executes the "next card" function, and tells Anki to fetch a new card and show it. So basically nothing happens to the card you skipped. I just goes back to the queue until Anki decides to show the card again. So the ARBb doesn't handle anything related to the ease/scheduling/queuing cards.

2. No, it doesn't change.

3. Short answer: Anki decides when to show you the card again.
2. Long answer: It's based on Anki's algorithm. If it thinks you have to see the card often, it might show you the card after like 2-3 cards. it usually happens with learning/re-learning cards. If the card is in review state though, you might end up reviewing many cards that are in queue before seeing the skipped card again.

hope this answers your questions. If any of the answers isn't clear enough, I'll be more than glad to answer you :D
