### ISSUE TITLE
New update causing issues (21/8/2024)

### ISSUE THREAD

**Issue by ndkumaragama** [noobj2/Anki-Advanced-Review-Bottombar#85]
It was working fine just before this error keeps coming up, where I can't even go through cards anymore. I would like to use it though for the skip function which I use a lot:

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.webview", line 628, in handler
  File "aqt.reviewer", line 761, in _onTypedAnswer
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\ndkum\AppData\Roaming\Anki2\addons21\1374772155\main.py", line 278, in on_show_answer
    return _old(self)
  File "aqt.reviewer", line 464, in _showAnswer
  File "aqt.reviewer", line 819, in _showEaseButtons
  File "C:\Users\ndkum\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 231, in _answerButtons
    buf += but(ease, label)
  File "C:\Users\ndkum\AppData\Roaming\Anki2\addons21\1136455830\Button_Colors.py", line 154, in but
    due_plain = re.search(r'<span.*>(.*?)</span>', self._buttonTime(i, v3_labels=labels)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T12:39, 'None', '']
Add Table ['1237621971', 2023-06-18T12:37, 'None', '']
Advanced Browser ['874215009', 2023-10-21T15:34, 'None', '']
Advanced Review Bottom Bar ['1136455830', 2024-08-21T10:31, 'None', '']
Anki OCR - Generate OCR text from images Fixed by Shige ['546383173', 2024-02-21T22:06, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T17:26, 'None', '']
Batch Editing ['291119185', 2023-10-26T01:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T16:25, 'None', '']
Color Confirmation ['1084228676', 2024-01-06T09:55, 'None', mod]
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T16:06, 'None', '']
Congrats Confetti ['206062158', 2023-01-17T04:02, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T12:50, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T02:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T09:17, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-01-03T07:19, '6.18', mod]
Enhance main window ['877182321', 2023-10-22T21:28, 'None', '']
Exam Notifier ['236593452', 2023-01-19T17:12, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-08-19T03:05, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T12:47, 'None', '']
Field AutoComplete ['511710206', 2024-07-20T15:07, 'None', mod]
Highlight Color Shortcut ['1178291236', 2021-04-01T17:42, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-21T20:17, 'None', '']
Image Editor ['307397307', 2022-09-08T05:09, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T08:15, 'None', '']
Large and Colorful Buttons ['1829090218', 2018-10-02T18:41, 'None', '']
Life Drain ['715575551', 2024-04-30T08:15, 'None', mod]
Maximum image height and width in card editor ['229181581', 2021-07-23T07:01, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T18:00, 'None', '']
Opening the same window multiple time ['354407385', 2023-11-05T01:59, 'None', '']
Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T07:26, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T12:59, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-19T04:15, 'None', '']
Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T15:14, 'None', '']
Remaining time for Anki 21 ['1508357010', 2024-04-16T03:15, '24.4.16i24', mod]
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
Shrink Image Size In Editor ['1633333766', 2022-10-21T10:23, 'None', '']
Special Fields ['1102281552', 2024-03-19T23:34, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T11:24, 'None', '']
True Retention ['613684242', 2017-11-19T20:43, 'None', '']
export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2024-03-28T13:16, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T15:12, 'None', mod]

===IDs of active AnkiWeb add-ons===
1046608507 1052724801 1084228676 1102281552 1136455830 1143540799 1178291236 1210908941 1237621971 1374772155 1508357010 1633333766 1642550423 1722658993 1771074083 1829090218 1967530655 206062158 225180905 229181581 236593452 24411424 2491935955 266436365 291119185 295889520 307397307 318752047 354407385 385888438 46611790 511710206 546383173 594329229 613684242 715575551 759844606 805891399 817108664 874215009 877182321

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Zoom ['538879081', 2020-04-04T01:20, 'v1.1.3', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-08-08T14:33, 'None', '']
Change Interface Font ['1431333984', 2023-11-17T15:34, 'None', mod]
Deck name in title 21 ['699175524', 2019-06-01T02:05, 'None', '']
External Note Editor for the Browser ['1996266159', 2020-03-31T21:59, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-19T23:49, 'None', '']
Picmonic Anki Add-On ['40737180', 2024-01-24T16:02, 'None', mod]
Replay buttons on card ['498789867', 2017-11-20T12:38, 'None', '']
Straight Reward ['957961234', 2023-11-01T14:11, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T05:42, 'None', '']
ZzLegacy HoochiePapa ['1173108619', 2020-04-25T04:17, 'None', '']

**Comment by noobj2** [comment]
can you go to preferences -> review and enable "show next review time above answer buttons" to see if that fixes the issue?

**Comment by qappell** [comment]
I had the same exact issue, and this removed the error for me.

**Comment by noobj2** [comment]
Fixed.
Thanks for the report @qappell @ndkumaragama
